version: '3'
services:
  db:
    image: postgres
    volumes:
      - stubby-postgres:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - stubby-redis:/var/lib/redis/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/stubby
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  stubby-postgres:
  stubby-redis: