default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

development:
  <<: *default
  database: stubby_dev

test:
  <<: *default
  database: stubby_test

production:
  <<: *default
  database: stubby_production